# Generated by Django 5.2.14 on 2026-05-31 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='體重')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='體脂肪率')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='腰圍')),
                ('recorded_at', models.DateTimeField(verbose_name='測量時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='health_heal_user_id_722f81_idx')],
            },
        ),
    ]
